config/routes.rb
Mauto::Application.routes.draw do

  root :to => "cars#index"

  resources :cars, :only => [:show] do
    post 'decide', :on => :collection
  end

end

app/models/car.rb
class Car < ActiveRecord::Base

	attr_accessor :score

	validates_presence_of :make, :model, :e_power, :e_horses, :e_space, :price, :built_at, :length
	validates_numericality_of :e_power, :e_horses, :e_space, :price, :length


	default_scope order("built_at DESC, updated_at DESC")

	def to_s
		"#{self.make} - #{self.model}"
	end

	def to_param
		"#{id}-#{self.make}-#{self.model}-#{self.built_at.strftime("%Y")}".parameterize
	end

end

app/models/decision.rb
class Decision

	include ActiveModel::Validations
	include ActiveModel::Conversion
	
	include ActiveSupport::Callbacks
	extend ActiveModel::Naming

	attr_accessor :built_at, :length, :engine, :price
	attr_accessor :e_power, :e_horses, :e_space
		
	validates_presence_of :built_at, :engine, :price, :e_power, :e_horses, :e_space
	validates_with DecisionDivisionValidator
	
	def initialize(attributes = {})
    	attributes.each do |name, value|
      		send("#{name}=", value)
    	end
    	self.default_values
  	end

  	def default_values
		self.built_at 	||= 0.25
		self.length 	||= 0.25
		self.engine 	||= 0.25
		self.e_power 		||=0.33
		self.e_horses 		||=0.33
		self.e_space 		||=0.33
		self.price  	||= 0.25
	end

	def importance
		{
			built_at: self.built_at,
			length: self.length,
				e_power: self.e_power*self.engine.to_f,
				e_horses: self.e_horses*self.engine.to_f,
				e_space: self.e_space*self.engine.to_f,
			price: self.price
		}
	end

	def benefit
		{
			built_at: Proc.new do |built_at, interes_f=0.5|
				max = Car.order("built_at DESC").limit(1).first.built_at.strftime("%Y").to_i
				(built_at.to_f/max.to_f) ** interes_f
			end,
			
			length: Proc.new do |price, interes_c=1.089, interes_f=3.5|
				interes_c+((price/Car.sum(:length)) ** interes_f)
			end,
			
			e_power: Proc.new do |e_power, interes_f=0.65|
				max = Car.maximum(:e_power)
				(e_power.to_f/max.to_f) ** interes_f
			end,
			
			e_horses: Proc.new do |e_horses, interes_f=0.94|
				max = Car.maximum(:e_horses)
				(e_horses.to_f/max.to_f) ** interes_f
			end,
			
			e_space: Proc.new do |e_space, interes_f=1.34|
				max = Car.maximum(:e_space)
				(e_space.to_f/max.to_f) ** interes_f
			end,

			price: Proc.new do |price, interes_c=1.089, interes_f=3.1|
				interes_c+((price/Car.sum(:price)) ** interes_f)
			end
		}		
	end

	def decide
		cars = Car.all.map! do |car|
			car.score = 0
			
			fields = %w(built_at length e_power e_horses e_space price).map! {|f| f.to_sym }

			fields.each do |field|
				car.score += self.benefit[field].call(car[field].to_f) * self.importance[field].to_f
			end

			car
		end

		cars.sort_by(&:score).reverse!
	end

	def persisted?
		false
	end

end

app/models/decision_division_validator.rb
class DecisionDivisionValidator < ActiveModel::Validator
	def validate(decision)
		total_level_one = [decision.built_at.to_f, decision.length.to_f, decision.engine.to_f, decision.price.to_f]
		if total_level_one.sum != 1
			decision.errors[:base] << "Decision division on top level must equal 1!
				Current: #{total_level_one.join("/")}=#{total_level_one.sum}"
		else
			total_level_two = [decision.e_power.to_f, decision.e_horses.to_f, decision.e_space.to_f]
			if total_level_two.sum < 0.85
				decision.errors[:base] << "Decision division on engine level must equal 1 (+/- 10%)!
					Current: #{total_level_two.join("/")}=#{total_level_two.sum}"				
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  
  respond_to :html, :js

  def index
  	@decision = Decision.new
  	@cars = @decision.decide
  end

  def show
  	@car = Car.find(params[:id])
  end

  def decide
  	@decision = Decision.new params[:decision]
  	
  	if @decision.valid?
  		@cars = @decision.decide
  	else
  		@cars = Decision.new.decide
	end

  	respond_with(@cars) do |f|
  		f.html { render :index }
  		f.js { render :decide, :layout => false}
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/views/cars/_car.haml
%li#car{:class => "car-#{car.id}"}
	.name=car
	= car.built_at.strftime("%Y")
	\/
	= number_to_human car.e_space, :units => { :unit => "ccm"}
	\/
	= number_to_human car.e_power,  :units => { :unit => "kW"}
	\/
	= number_to_human car.e_horses, :units => { :unit => "KM"}
	\/
	= number_to_human car.length, :units => { :unit => "km" }
	\/
	%strong.price= number_to_currency car.price, :unit => "&euro;"

	- unless car.score.nil?
		.score=number_to_human car.score, :precision => 5
	
	
	

app/views/cars/_maut_form.haml
=form_for(@decision, :url => decide_cars_url(), :remote => true) do |f|

	- if not f.object.errors.empty?
		%ul.errors
			- f.object.errors.each do |e,val|
				%li=val
	
	%table
		%tbody
			%tr
				%th Built at
				%td=f.text_field :built_at, :size => "10"
			%tr
				%th Number of km
				%td=f.text_field :length, :size => "10"			
			%tr
				%th(valign="top") Engine
				%td(valign="top")
					=f.text_field :engine, :size => "10"			

					%table
						%tbody
							%tr
								%th Power
								%td=f.text_field :e_power, :size => "10"						
							%tr
								%th Horses
								%td=f.text_field :e_horses, :size => "10"						
							%tr
								%th Space
								%td=f.text_field :e_space, :size => "10"							
			%tr
				%th Price
				%td=f.text_field :price, :size => "10"
			%tr
				%td(colspan="2")
					=f.submit "Filter"

app/views/cars/decide.js.erb
$("#maut_form").html('<%= j render "maut_form" %>');
$("#cars_list").html('<ul id="cars"><% @cars.each do |car| %><%= j render car %><% end %></ul>');

app/views/cars/index.html.haml
#maut_form=render "maut_form"

#cars_list
	- unless @cars.nil?
		%ul#cars=render @cars

app/views/layouts/application.haml
!!!
%html
	%head
		= stylesheet_link_tag    "application"
		= javascript_include_tag "application"
		= csrf_meta_tags
		%link(href='http://fonts.googleapis.com/css?family=Istok+Web' rel='stylesheet' type='text/css')
		%title mauto - Experimenting with MAUT
	
	%body
		.container
			.header
				%h1
					=link_to root_path() do
						Finding best car using MAUT.
				%p
					=link_to "Multi-Attribute Utility Theory(MAUT)", "http://en.wikipedia.org/wiki/Multi-criteria_decision_analysis"
					is sub-discipline of 
					=link_to "operations research", "http://en.wikipedia.org/wiki/Operations_research"
					that explicitly considers multiple criteria in decision-making environments.
			.main
			
				= yield

			.footer
				=link_to sanitize("&copy; 2011 - Oto Brglez / opalab"), "http://opalab.com"
				|
				=link_to "Source code @ GitHub", "https://github.com/otobrglez/mauto"